# Generated by Django 3.2.23 on 2023-11-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Consumer Name')),
                ('email', models.EmailField(max_length=277, verbose_name='Consumer Email')),
            ],
        ),
    ]
