# Generated by Django 3.2.23 on 2023-11-11 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20231111_1946'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Consumer',
        ),
    ]
