# Generated by Django 3.2.23 on 2023-12-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fo_hz', models.FloatField()),
                ('fhi_hz', models.FloatField()),
                ('flo_hz', models.FloatField()),
                ('jitter_percent', models.FloatField()),
                ('jitter_abs', models.FloatField()),
                ('rap', models.FloatField()),
                ('ppq', models.FloatField()),
                ('jitter_ddp', models.FloatField()),
                ('shimmer', models.FloatField()),
                ('shimmer_db', models.FloatField()),
                ('shimmer_apq3', models.FloatField()),
                ('shimmer_apq5', models.FloatField()),
                ('mdvp_apq', models.FloatField()),
                ('shimmer_dda', models.FloatField()),
                ('nhr', models.FloatField()),
                ('hnr', models.FloatField()),
                ('rpde', models.FloatField()),
                ('dfa', models.FloatField()),
                ('spread1', models.FloatField()),
                ('spread2', models.FloatField()),
                ('d2', models.FloatField()),
                ('ppe', models.FloatField()),
            ],
        ),
    ]
