# Generated by Django 3.2.23 on 2023-12-18 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_userinput'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkinsonsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('MDVP_Fo', models.FloatField(default=0.0)),
                ('MDVP_Fhi', models.FloatField(default=0.0)),
                ('MDVP_Flo', models.FloatField(default=0.0)),
                ('MDVP_Jitter_percent', models.FloatField(default=0.0)),
                ('MDVP_Jitter_Abs', models.FloatField(default=0.0)),
                ('MDVP_RAP', models.FloatField(default=0.0)),
                ('MDVP_PPQ', models.FloatField(default=0.0)),
                ('Jitter_DDP', models.FloatField(default=0.0)),
                ('MDVP_Shimmer', models.FloatField(default=0.0)),
                ('MDVP_Shimmer_dB', models.FloatField(default=0.0)),
                ('Shimmer_APQ3', models.FloatField(default=0.0)),
                ('Shimmer_APQ5', models.FloatField(default=0.0)),
                ('MDVP_APQ', models.FloatField(default=0.0)),
                ('Shimmer_DDA', models.FloatField(default=0.0)),
                ('NHR', models.FloatField(default=0.0)),
                ('HNR', models.FloatField(default=0.0)),
                ('status', models.IntegerField(default=0)),
                ('RPDE', models.FloatField(default=0.0)),
                ('DFA', models.FloatField(default=0.0)),
                ('spread1', models.FloatField(default=0.0)),
                ('spread2', models.FloatField(default=0.0)),
                ('D2', models.FloatField(default=0.0)),
                ('PPE', models.FloatField(default=0.0)),
            ],
        ),
        migrations.DeleteModel(
            name='UserInput',
        ),
    ]
