# Generated by Django 5.0.3 on 2024-04-11 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FetalHealthInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("baseline_fhr", models.FloatField()),
                ("accelerations", models.FloatField()),
                ("fetal_movement", models.FloatField()),
                ("uterine_contractions", models.FloatField()),
                ("light_decelerations", models.FloatField()),
                ("severe_decelerations", models.FloatField()),
                ("prolongued_decelerations", models.FloatField()),
                ("abnormal_short_term_variability", models.FloatField()),
                ("mean_value_of_short_term_variability", models.FloatField()),
                (
                    "percentage_of_time_with_abnormal_long_term_variability",
                    models.FloatField(),
                ),
                ("mean_value_of_long_term_variability", models.FloatField()),
                ("histogram_width", models.FloatField()),
                ("histogram_min", models.FloatField()),
                ("histogram_max", models.FloatField()),
                ("histogram_number_of_peaks", models.IntegerField()),
                ("histogram_number_of_zeroes", models.IntegerField()),
                ("histogram_mode", models.FloatField()),
                ("histogram_mean", models.FloatField()),
                ("histogram_median", models.FloatField()),
                ("histogram_variance", models.FloatField()),
                ("histogram_tendency", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("fetal_health", models.IntegerField()),
                ("delivery_type", models.CharField(max_length=20)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
