# Generated by Django 5.0.3 on 2024-04-12 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fetal_health", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fetalhealthinput",
            old_name="histogram_number_of_peaks",
            new_name="baseline_value",
        ),
        migrations.RemoveField(
            model_name="fetalhealthinput",
            name="baseline_fhr",
        ),
        migrations.RemoveField(
            model_name="fetalhealthinput",
            name="histogram_max",
        ),
        migrations.RemoveField(
            model_name="fetalhealthinput",
            name="histogram_mean",
        ),
        migrations.RemoveField(
            model_name="fetalhealthinput",
            name="histogram_median",
        ),
        migrations.RemoveField(
            model_name="fetalhealthinput",
            name="histogram_min",
        ),
        migrations.RemoveField(
            model_name="fetalhealthinput",
            name="histogram_mode",
        ),
        migrations.RemoveField(
            model_name="fetalhealthinput",
            name="histogram_number_of_zeroes",
        ),
        migrations.RemoveField(
            model_name="fetalhealthinput",
            name="histogram_tendency",
        ),
        migrations.RemoveField(
            model_name="fetalhealthinput",
            name="histogram_variance",
        ),
        migrations.RemoveField(
            model_name="fetalhealthinput",
            name="histogram_width",
        ),
        migrations.AlterField(
            model_name="fetalhealthinput",
            name="accelerations",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="fetalhealthinput",
            name="fetal_health",
            field=models.IntegerField(
                choices=[(1, "Normal"), (2, "Suspect"), (3, "Pathological")]
            ),
        ),
        migrations.AlterField(
            model_name="fetalhealthinput",
            name="fetal_movement",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="fetalhealthinput",
            name="light_decelerations",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="fetalhealthinput",
            name="prolongued_decelerations",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="fetalhealthinput",
            name="severe_decelerations",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="fetalhealthinput",
            name="uterine_contractions",
            field=models.IntegerField(),
        ),
    ]
